import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";

function Posts({ data }) {
  const router = useRouter();

  const [show, setShow] = useState(3);

  const addNewPost = async () => {
    const response = await fetch(`http://localhost:3000/api/post`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: "New Post",
        body: "New body",
      }),
    });

    const data = await response.json();
    console.log(data);
  };
  return (
    <div className="container">
      <Head>
        <title>All Posts</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="my-5 d-flex justify-content-around">
        <mark>All Posts</mark>
        <button
          onClick={() => router.back()}
          style={{
            fontSize: "30px",
            color: "white",
            backgroundColor: "grey",
            borderRadius: "10px",
          }}
        >
          Go Back
        </button>
      </h1>

      {data?.slice(0, show)?.map((post, id) => (
        <div key={id} className="mb-5">
          <h3
            className="d-flex underline"
            onClick={() => router.push(`posts/${post.id}`)}
          >
            <ins className="d-flex">
              <div className="fs-18">
                {post.id}.{"  "}
              </div>{" "}
              {post.name}
            </ins>
          </h3>
          <h6 className="">Email: {post.email}</h6>
          <p className="pl-4">Description: {post.body}</p>
        </div>
      ))}

      <button
        onClick={() => setShow(show + 3)}
        style={{
          fontSize: "30px",
          color: "white",
          display: "flex",
          margin: "auto",
          marginTop: "20px",
          backgroundColor: "grey",
          borderRadius: "10px",
        }}
      >
        Show more
      </button>
      <button onClick={addNewPost}>Add</button>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    "https://jsonplaceholder.typicode.com/comments?_limit=50"
  );

  const data = await response.json();

  return {
    props: {
      data,
    },
    revalidate: 10,
  };
}

export default Posts;
